export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const GET_PROJECT_BEGIN = "GET_PROJECT_BEGIN";
export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS";
export const GET_PROJECT_ERROR = "GET_PROJECT_ERROR";

export const GET_SINGLE_PROJECT_BEGIN = "GET_SINGLE_PROJECT_BEGIN";
export const GET_SINGLE_PROJECT_SUCCESS = "GET_SINGLE_PROJECT_SUCCESS";
export const GET_SINGLE_PROJECT_ERROR = "GET_SINGLE_PROJECT_ERROR";

export const CREATE_PROJECT_BEGIN = "CREATE_PROJECT_BEGIN";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_ERROR = "CREATE_PROJECT_ERROR";

export const HANDLE_CHANGE = "HANDLE_CHANGE";

export const CLEAR_VALUES = "CLEAR_VALUES";

export const GET_PROJECT_TICKET_BEGIN = "GET_PROJECT_TICKET_BEGIN";
export const GET_PROJECT_TICKET_SUCCESS = "GET_PROJECT_TICKET_SUCCESS";
export const GET_PROJECT_TICKET_ERROR = "GET_PROJECT_TICKET_ERROR";

export const GET_MY_TICKET_BEGIN = "GET_MY_TICKET_BEGIN";
export const GET_MY_TICKET_SUCCESS = "GET_MY_TICKET_SUCCESS";
export const GET_MY_TICKET_ERROR = "GET_MY_TICKET_ERROR";

export const GET_USER_PROJECT_BEGIN = "GET_USER_PROJECT_BEGIN";
export const GET_USER_PROJECT_SUCCESS = "GET_USER_PROJECT_SUCCESS";
export const GET_USER_PROJECT_ERROR = "GET_USER_PROJECT_ERROR";

export const EDIT_USER_INFO_BEGIN = "EDIT_USER_INFO_BEGIN";
export const EDIT_USER_INFO_SUCCESS = "EDIT_USER_INFO_SUCCESS";
export const EDIT_USER_INFO_ERROR = "EDIT_USER_INFO_ERROR";
